version: "3.1"
services:

  mongo:
    image: bitnami/mongodb:4.4
    environment:
      MONGODB_REPLICATE_SET_MODE: primary
    ports:
      - "27017:27017"

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - vt_redis_data:/data

  postgres:
    image: postgres:13.1
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: virtool
      POSTGRES_PASSWORD: virtool
    volumes:
      - vt_postgres_data:/var/lib/postgresql/data

  jobs-api:
    image: virtool/virtool:7.2.2
    depends_on:
      - mongo
      - redis
      - postgres
    command: >
      --db-connection-string="mongodb://mongo:27017"
      --db-name="test"
      --postgres-connection-string="postgresql+asyncpg://virtool:virtool@postgres/virtool"
      --redis-connection-string="redis://redis:6379"
      --dev
      jobsAPI
      --host=0.0.0.0
      --port=9990
    ports:
      - "9990:9990"

volumes:
  vt_mongo_data:
  vt_redis_data:
  vt_postgres_data:
