services:
  redis:
    image: redis:6.0
    command: redis-server --requirepass virtool
    networks:
      - virtool_workflow_network
    ports:
      - 6379:6379

networks:
  virtool_workflow_network:
    driver: bridge
