version: "3.1"
services:
  jobs-api:
    image: virtool/virtool:13.4.2
    command: jobsAPI --host=0.0.0.0 --port=9990
    depends_on:
      - mongo
      - openfga
      - postgres
      - redis
    environment:
      VT_DB_NAME: test
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017/test
      VT_DEV: "true"
      VT_OPENFGA_HOST: openfga:8080
      VT_OPENFGA_SCHEME: http
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    ports:
      - "9990:9990"

  mongo:
    image: bitnami/mongodb:4.4
    environment:
      MONGODB_REPLICATE_SET_MODE: primary
    ports:
      - "27017:27017"

  postgres:
    image: postgres:14.5
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: virtool
      POSTGRES_PASSWORD: virtool

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  openfga-postgres:
    image: postgres:14.5
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 300ms
      retries: 12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openfga

  openfga-migration:
    image: openfga/openfga:v0.2.5
    command: migrate
    depends_on:
      openfga-postgres:
        condition: service_healthy
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://postgres:password@openfga-postgres:5432/openfga

  openfga:
    image: openfga/openfga:v0.2.5
    command: run
    depends_on:
      openfga-migration:
        condition: service_started
    environment:
      OPENFGA_DATASTORE_ENGINE: postgres
      OPENFGA_DATASTORE_URI: postgres://postgres:password@openfga-postgres:5432/openfga
    ports:
      - "8080:8080"
      - "3000:3000"
