apiVersion: v1
kind: Service
metadata:
  name: jobs-api
  namespace: default
spec:
  selector:
    app: jobs-api
  type: NodePort
  ports:
    - name: tcp-port
      port: 9990
      targetPort: 9990
      protocol: TCP
