services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached

  redis:
    image: redis:6.0
    command: redis-server --requirepass virtool
    ports:
      - 6379:6379
