name: Release Workflow Docker Image

on:
  release:
    types: [ created ]
  
  workflow_run:
    workflows:
      - "Create Github Release"
    branches:
      - master
    types:
      - completed 

  workflow_dispatch:

jobs:
  publish_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version Number
        id: get_version
        run: | 
            pip install poetry
            echo "##[set-output name=version;]$(poetry version | cut -f2 -d' ')"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: virtool/workflow:${{ steps.get_version.outputs.version }}

      - name: Update README on Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: virtool/workflow
          readme-filepath: ./docker/README.md

