# Run the virtool-workflow integration tests
#
name: Integration Tests

on:
  pull_request:
    branches:
      - "master"
      - "release/*"
      - "develop"

  workflow_dispatch:

jobs:

  integration-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build `virtool/workflow`
        run: docker build -t virtool/workflow .

      - name: Run Tests Using Docker Compose
        run: |
          pip install .
          cd integration_tests
          ./run.sh
