name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "22 22 * * *"

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: virtool/workflow:nightly
      - name: Image Digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Update README on Docker Hub
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: virtool/workflow
          readme-filepath: ./docker/README.md
