name: publish

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io

jobs:
  pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Update Version
        run: poetry version ${{github.event.release.tag_name}}
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_TOKEN }}
  ghcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: github.repository_owner == 'Virtool'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Setup Poetry
      uses: snok/install-poetry@v1
    - name: Update Version
      run: poetry version ${{github.event.release.tag_name}}
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Extract Metadata
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/virtool/workflow
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
